package com.niltonvasques.fosfrinho.components;

public enum Message {
	BOB_FACING_LEFT, BOB_FACING_RIGHT, BOB_DAMAGED, 
	
	BTN_LEFT_PRESSED, BTN_RIGHT_PRESSED, BTN_LEFT_RELEASED, BTN_RIGHT_RELEASED,
	BOB_JUMP_PRESSED, BOB_JUMP_RELEASED, GROUNDED, FLYING
}
