package com.niltonvasques.fosfrinho.components.comm;

public enum Message {
	DAMAGED, FIRE, 
	BOB_JUMP_PRESSED, BOB_JUMP_RELEASED, GROUNDED, FLYING,	
	WALKING, IDLE, BOB_JUMPING, BOB_FALLING,	
	
	BTN_LEFT_PRESSED, BTN_RIGHT_PRESSED, BTN_LEFT_RELEASED, BTN_RIGHT_RELEASED,
	BTN_PLUS, BTN_MINUS,
		
	DEBUG, 
	
	DEAD, DISPOSE, ADD_STAGE	
	
}
